name: angular_tour_of_heroes
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  http: ^0.12.0+4
  stream_transform: ^0.0.20

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.8.0
  build_test: ^0.10.12+1
  build_web_compilers: ^2.9.0
  mockito: ^3.0.2
  pageloader: ^3.2.2
  test: ^1.6.3

transformers:
  - $dart2js:
      sourceMaps: true
